ai:
    platform:
        # Inference Platform configuration
        # see https://github.com/symfony/ai/tree/main/src/platform#platform-bridges

        # openai:
        #    api_key: '%env(OPENAI_API_KEY)%'

    agent:
        # Agent configuration
        # see https://symfony.com/doc/current/ai/bundles/ai-bundle.html

        # default:
        #    platform: 'ai.platform.openai'
        #    model: 'gpt-5-mini'
        #    prompt: |
        #        You are a pirate and you write funny.
        #    tools:
        #        - 'Symfony\AI\Agent\Bridge\Clock\Clock'

        plant_finder:
            platform: 'ai.platform.sulu_ai_platform'
            model:
                name: 'agent'
                options: { name: 'plant-finder', ttl_days: 1, model: 'gemini-3.7-flash', server_tools: ['ask_user'] }
            max_tool_calls: 8
            prompt:
                file: '%kernel.project_dir%/config/ai/plant_finder.md'
            tools:
                - 'App\Ai\GetWeather'
                - 'sulu_product.ai_get_attributes'
                - 'sulu_product.ai_get_attribute_values'
                - 'sulu_product.ai_search_products_by_attributes'
                - 'sulu_product.ai_get_product_details'

    store:
        # Store configuration

        # chromadb:
        #    default:
        #        client: 'client.service.id'
        #        collection: 'my_collection'
